<?php

/**
 * @file
 * Contains welcome.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function welcome_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the welcome module.
    case 'help.page.welcome':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Display a message when a user logs in') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_user_login().
 *
 * @param $account
 */
function welcome_user_login($account) {
  $config = \Drupal::config('welcome.adminsettings');
  \Drupal::messenger()->addMessage(t('Hi @name ' . $config->get('welcome_message', array('@name' => $account->name))));
}
